-- Lumberton Lock In — full Supabase setup
-- Run this once against a fresh Supabase project's SQL Editor.
-- (If you're pointing this repo at the SAME Supabase project that's already
-- working, you don't need to run this again — it's here for reference or
-- for setting up a new project from scratch.)

-- ---------- Tables ----------

create table if not exists activity_log (
  id bigint generated by default as identity primary key,
  agent text not null,
  session text not null,
  dials int not null default 0,
  contacts int not null default 0,
  appts int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists apps_log (
  id bigint generated by default as identity primary key,
  agent text not null,
  session text not null,
  carrier text not null,
  apv numeric not null default 0,
  apps int not null default 1,
  created_at timestamptz not null default now()
);

-- ---------- Row Level Security ----------

alter table activity_log enable row level security;
alter table apps_log enable row level security;

-- ---------- Base table grants ----------
-- RLS policies control which ROWS a role can touch, but the role also needs
-- basic table-level privileges to touch the table at all — this is that grant.

grant usage on schema public to anon, authenticated;

grant select, insert on activity_log to anon;
grant select, insert, update, delete on activity_log to authenticated;

grant select, insert on apps_log to anon;
grant select, insert, update, delete on apps_log to authenticated;

-- ---------- Policies ----------
-- Public (anon) visitors can log new entries and read the leaderboard.
-- Only a signed-in (authenticated) admin user can edit or delete entries.

create policy "Public can insert activity"
  on activity_log for insert
  to anon
  with check (true);

create policy "Public can read activity"
  on activity_log for select
  to anon
  using (true);

create policy "Authenticated can read activity"
  on activity_log for select
  to authenticated
  using (true);

create policy "Authenticated can update activity"
  on activity_log for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated can delete activity"
  on activity_log for delete
  to authenticated
  using (true);

create policy "Public can insert apps"
  on apps_log for insert
  to anon
  with check (true);

create policy "Public can read apps"
  on apps_log for select
  to anon
  using (true);

create policy "Authenticated can read apps"
  on apps_log for select
  to authenticated
  using (true);

create policy "Authenticated can update apps"
  on apps_log for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated can delete apps"
  on apps_log for delete
  to authenticated
  using (true);
